model {
  file: "model.sdf"
}
name: "Closetmaid_Premium_Fabric_Cube_Red"
description: "Closetmaid Premium Fabric Cube - Red"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Closetmaid"
}
annotations {
  key: "gtin"
  value: "00075381160841"
}
annotations {
  key: "sku"
  value: "00075381160841"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
