<?xml version="1.0"?>
<robot name="gripper" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="scout_mini_gripper"
               params="
                 parent:=base_link
                 mount_xyz:='0.40 0 0.20'
                 mount_rpy:='0 0 0'
                 jaw_length:=0.16
                 jaw_thickness:=0.02
                 jaw_height:=0.05
                 frame_width:=0.28
                 opening_max:=0.16
                 density:=7800">

    <xacro:macro name="gr_inertial_box" params="x y z rho">
      <inertial>
        <mass value="${rho * x * y * z}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="${(1.0/12.0)*rho*x*y*z*(y*y+z*z)}"
                 ixy="0" ixz="0"
                 iyy="${(1.0/12.0)*rho*x*y*z*(x*x+z*z)}"
                 iyz="0"
                 izz="${(1.0/12.0)*rho*x*y*z*(x*x+y*y)}"/>
      </inertial>
    </xacro:macro>

    <link name="gripper_base">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="0.08 0.30 0.06"/></geometry>
        <material name="Gray"><color rgba="0.5 0.5 0.5 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="0.08 0.30 0.06"/></geometry>
      </collision>
      <xacro:gr_inertial_box x="0.08" y="0.30" z="0.06" rho="${density}"/>
    </link>

    <joint name="gripper_mount_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="gripper_base"/>
      <origin xyz="${mount_xyz}" rpy="${mount_rpy}"/>
    </joint>

    <link name="left_finger">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="${jaw_length} ${jaw_thickness} ${jaw_height}"/></geometry>
        <material name="Black"><color rgba="0.1 0.1 0.1 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="${jaw_length} ${jaw_thickness} ${jaw_height}"/></geometry>
      </collision>
      <xacro:gr_inertial_box x="${jaw_length}" y="${jaw_thickness}" z="${jaw_height}" rho="${density}"/>
    </link>

    <link name="right_finger">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="${jaw_length} ${jaw_thickness} ${jaw_height}"/></geometry>
        <material name="Black2"><color rgba="0.2 0.2 0.2 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="${jaw_length} ${jaw_thickness} ${jaw_height}"/></geometry>
      </collision>
      <xacro:gr_inertial_box x="${jaw_length}" y="${jaw_thickness}" z="${jaw_height}" rho="${density}"/>
    </link>

    <link name="u_frame_bar_top">
      <visual>
        <origin xyz="0.02 0 ${0.5*jaw_height+0.02}"/>
        <geometry><box size="0.04 ${frame_width} 0.02"/></geometry>
        <material name="Gray2"><color rgba="0.6 0.6 0.6 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="0.02 0 ${0.5*jaw_height+0.02}"/>
        <geometry><box size="0.04 ${frame_width} 0.02"/></geometry>
      </collision>
      <xacro:gr_inertial_box x="0.04" y="${frame_width}" z="0.02" rho="${density}"/>
    </link>

    <joint name="u_frame_top_fix" type="fixed">
      <parent link="gripper_base"/>
      <child link="u_frame_bar_top"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="left_finger_joint" type="prismatic">
      <parent link="gripper_base"/>
      <child link="left_finger"/>
      <origin xyz="0.04 ${0.5*frame_width - 0.5*jaw_thickness} 0.0" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit lower="0.0" upper="${0.5*opening_max}" effort="200" velocity="0.3"/>
      <dynamics damping="2.0" friction="0.1"/>
    </joint>

    <joint name="right_finger_joint" type="prismatic">
      <parent link="gripper_base"/>
      <child link="right_finger"/>
      <origin xyz="0.04 ${-0.5*frame_width + 0.5*jaw_thickness} 0.0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="0.0" upper="${0.5*opening_max}" effort="200" velocity="0.3"/>
      <dynamics damping="2.0" friction="0.1"/>
    </joint>

    <gazebo reference="gripper_base"><kp>20000</kp><kd>50</kd></gazebo>
    <gazebo reference="left_finger"><mu1>1.0</mu1><mu2>1.0</mu2></gazebo>
    <gazebo reference="right_finger"><mu1>1.0</mu1><mu2>1.0</mu2></gazebo>

    <ros2_control name="gripper_ros2_control" type="system">
      <hardware><plugin>gazebo_ros2_control/GazeboSystem</plugin></hardware>
      <joint name="left_finger_joint">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>
      <joint name="right_finger_joint">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>
    </ros2_control>

  </xacro:macro>
</robot>