<?xml version="1.0"?>
<robot name="scout_mini_gripper" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="scout_mini_gripper" params="parent mount_x:=0.40 mount_y:=0.0 mount_z:=0.20 opening_max:=0.18">

    <xacro:property name="finger_len" value="0.20"/>
    <xacro:property name="finger_thk" value="0.02"/>
    <xacro:property name="closed_gap" value="0.002"/>
    <xacro:property name="half_thk" value="${finger_thk/2.0}"/>
    <xacro:property name="half_gap" value="${closed_gap/2.0}"/>
    <xacro:property name="open_default" value="0.06"/>

    <xacro:property name="brace_thk" value="0.02"/>
    <xacro:property name="pillar_len" value="${mount_z}"/>   <!-- 세로(높이) -->
    <xacro:property name="arm_len"    value="${mount_x}"/>   <!-- 가로(전방) -->

    <link name="gripper_pillar">
      <visual>
        <geometry><box size="${brace_thk} ${brace_thk} ${pillar_len}"/></geometry>
        <material name="Grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
      </visual>
      <collision><geometry><box size="${brace_thk} ${brace_thk} ${pillar_len}"/></geometry></collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0002" iyy="0.0002" izz="0.00002" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="gripper_pillar_mount" type="fixed">
      <parent link="${parent}"/>
      <child  link="gripper_pillar"/>
      <origin xyz="0 ${mount_y} ${pillar_len/2.0}" rpy="0 0 0"/>
    </joint>

    <link name="gripper_arm">
      <visual>
        <geometry><box size="${arm_len} ${brace_thk} ${brace_thk}"/></geometry>
        <material name="Grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
      </visual>
      <collision><geometry><box size="${arm_len} ${brace_thk} ${brace_thk}"/></geometry></collision>
      <inertial>
        <mass value="0.15"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.00005" iyy="0.00005" izz="0.00002" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="pillar_to_arm" type="fixed">
      <parent link="gripper_pillar"/>
      <child  link="gripper_arm"/>
      <origin xyz="${arm_len/2.0} 0 ${pillar_len/2.0}" rpy="0 0 0"/>
    </joint>

    <link name="gripper_base">
      <visual>
        <geometry><box size="0.02 0.25 0.05"/></geometry>
        <material name="Grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
      </visual>
      <collision><geometry><box size="0.02 0.25 0.05"/></geometry></collision>
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.002" iyy="0.002" izz="0.002" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="arm_to_gripper_base" type="fixed">
      <parent link="gripper_arm"/>
      <child  link="gripper_base"/>
      <origin xyz="${arm_len/2.0} 0 0" rpy="0 0 0"/>
    </joint>

    <link name="left_finger">
      <visual>
        <geometry><box size="${finger_len} ${finger_thk} 0.04"/></geometry>
        <material name="Grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
      </visual>
      <collision><geometry><box size="${finger_len} ${finger_thk} 0.04"/></geometry></collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0001" iyy="0.0002" izz="0.0002" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="left_finger_joint" type="prismatic">
      <parent link="gripper_base"/>
      <child  link="left_finger"/>
      <origin xyz="0.1 ${half_thk + half_gap + open_default} 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-open_default}" upper="${opening_max/2.0 - open_default}" effort="200" velocity="1.0"/>
      <dynamics damping="5.0" friction="0.1"/>
    </joint>

    <link name="right_finger">
      <visual>
        <geometry><box size="${finger_len} ${finger_thk} 0.04"/></geometry>
        <material name="Grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
      </visual>
      <collision><geometry><box size="${finger_len} ${finger_thk} 0.04"/></geometry></collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0001" iyy="0.0002" izz="0.0002" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="right_finger_joint" type="prismatic">
      <parent link="gripper_base"/>
      <child  link="right_finger"/>
      <origin xyz="0.1 ${-(half_thk + half_gap + open_default)} 0"/>
      <axis xyz="0 -1 0"/>
      <limit lower="${-open_default}" upper="${opening_max/2.0 - open_default}" effort="200" velocity="1.0"/>
      <dynamics damping="5.0" friction="0.1"/>
    </joint>

    <ros2_control name="gripper_ros2_control" type="system">
      <hardware>
        <plugin>gazebo_ros2_control/GazeboSystem</plugin>
      </hardware>
      <joint name="left_finger_joint">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>
      <joint name="right_finger_joint">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>
    </ros2_control>
  </xacro:macro>

  <gazebo reference="gripper_base">
    <material>Gazebo/Grey</material>
  </gazebo>
    <gazebo reference="left_finger">
  <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="right_finger">
    <material>Gazebo/Grey</material>
  </gazebo>
</robot>
