controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    gripper_controller:
      type: position_controllers/JointGroupPositionController
    gripper_height_controller:
      type: position_controllers/JointGroupPositionController


gripper_controller:
  ros__parameters:
    joints:
      - left_finger_joint
      - right_finger_joint

gripper_height_controller:
  ros__parameters:
    joints:
      - connecter_to_arm


# 필요시 p를 100~400 사이에서 조정.
gazebo_ros2_control:
  ros__parameters:
    pid_gains:
      left_finger_joint:  {p: 200.0, i: 1.0, d: 5.0, i_clamp_min: -0.5, i_clamp_max: 0.5}
      right_finger_joint: {p: 200.0, i: 1.0, d: 5.0, i_clamp_min: -0.5, i_clamp_max: 0.5}
      connecter_to_arm:  {p: 350.0, i: 1.0, d: 10.0, i_clamp_min: -0.5, i_clamp_max: 0.5}

